export const TYPE_CARD = "CARD";
export const DROPPABLE_INVENTORY = "INVENTORY_DROPPABLE";
export const DROPPABLE_SELECT = "SELECT_DROPPABLE";
export const DROPPABLE_UNSELECT = "UNSELECTED_DROPPABLE";
