export const SELECT_WORKER = "SELECT_WORKER";
export const UNSELECT_WORKER = "UNSELECT_WORKER";
export const REMOVE_FROM_INVENTORY = "REMOVE_FROM_INVENTORY";
export const ADD_TO_SELECTED = "ADD_TO_SELECTED";
export const ADD_TO_UNSELECTED = "ADD_TO_UNSELECTED";

export const FETCH_WORKERS_SUCCESS = "FETCH_WORKERS_SUCCESS";
export const FETCH_WORKERS_FAILURE = "FETCH_WORKERS_FAILURE";
